# Generated by Django 5.0.6 on 2024-09-28 06:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turf', '0003_alter_swimmingslot_field_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='swimmingslot',
            options={'ordering': ['date', 'session__start_time']},
        ),
        migrations.AlterField(
            model_name='swimmingslot',
            name='number_of_people',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='swimmingslot',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SwimmingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.PositiveIntegerField(default=20)),
            ],
            options={
                'ordering': ['start_time'],
                'unique_together': {('start_time', 'end_time')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='swimmingslot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='swimmingslot',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='Turf.swimmingsession'),
        ),
        migrations.AlterUniqueTogether(
            name='swimmingslot',
            unique_together={('turf', 'date', 'session')},
        ),
        migrations.RemoveField(
            model_name='swimmingslot',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='swimmingslot',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='swimmingslot',
            name='start_time',
        ),
    ]
