# Generated by Django 5.0.6 on 2024-09-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turf', '0005_remove_swimmingslot_advance_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swimmingsession',
            name='capacity',
        ),
        migrations.AddField(
            model_name='swimmingslot',
            name='capacity',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='swimmingslot',
            name='price',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=6),
        ),
    ]
