# Generated by Django 5.0.6 on 2024-09-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turf', '0006_remove_swimmingsession_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='swimmingsession',
            name='capacity',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
