# Generated by Django 5.0.6 on 2024-09-28 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turf', '0007_swimmingsession_capacity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='swimmingslot',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='swimmingslot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='swimmingsession',
            name='price_per_person',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='swimmingslot',
            name='field_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Turf.fieldsize'),
        ),
        migrations.AlterField(
            model_name='swimmingslot',
            name='number_of_people',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='swimmingslot',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Turf.swimmingsession'),
        ),
        migrations.AlterField(
            model_name='swimmingslot',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='swimmingslot',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='swimmingslot',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='swimmingslot',
            name='price',
        ),
    ]
