# Generated by Django 5.0.6 on 2024-09-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offers', '0001_initial'),
        ('Turf', '0008_alter_swimmingslot_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='availble_offers',
            field=models.ManyToManyField(to='Offers.coupon'),
        ),
        migrations.AddField(
            model_name='turf',
            name='sports',
            field=models.CharField(blank=True, choices=[('Cricket', 'Cricket'), ('Football', 'Football'), ('Swimming', 'Swimming'), ('Badminton', 'Badminton')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='swimmingsession',
            name='price_per_person',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=6),
        ),
    ]
